
name: 'Close stale issues'
on:
  schedule:
    - cron: '0 10 * * 1-5'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          exempt-issue-labels: "keep"
          any-of-labels: "needs-more-info"
          start-date: "2023-01-01T00:00:00Z"
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed automatically shortly.'
          days-before-issue-stale: 14
          days-before-issue-close: 2
          operations-per-run: 1000
          close-issue-label: "wontfix"
          close-issue-reason: "not_planned"
          debug-only: false
